all:
  hosts:
    10.0.200.23:
      ansible_user: jenkins                
      ansible_ssh_private_key_file: /home/jks/.ssh/id_rsa  
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ConnectTimeout=30'
